---
# 5) (Optional) Argo CD Application - points to /k8s-manifests in your repo
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/chandika-s/Argo-BootCamp-2025.git'  
    targetRevision: HEAD
    path: k8s-manifests                               # <-- path you mentioned
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false